### ISSUE TITLE
Error in Sreach_lib.py

### ISSUE THREAD

**Issue by Radhu903** [petermr/openDiagram#5]
```
C:\Users\DELL\AppData\Local\Programs\Python\Python39\python.exe C:/Users/DELL/Radhu/openDiagram/physchem/python/search_lib.py
running search main
DEMO
Traceback (most recent call last):
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 557, in <module>
    main()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 533, in main
    AmiSearch.demo()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 201, in demo
    ami_search = AmiSearch()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 49, in __init__
    self.ami_projects = AmiProjects()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 276, in __init__
    self.create_project_dict()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 280, in create_project_dict
    self.add_with_check(AmiProjects.LIION10, os.path.join(PHYSCHEM_RESOURCES, "liion10"))
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 295, in add_with_check
    Util.check_exists(file)
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\util.py", line 291, in check_exists
    assert os.path.exists(file), str(file) + " should exist"
AssertionError: C:\Users\DELL\projects\openDiagram\physchem\resources\liion10 should exist

Process finished with exit code 1

```

**Comment by Radhu903** [comment]
#commandlines errors
```
C:\Users\DELL>cd Radhu\openDiagram\physchem\python

C:\Users\DELL\Radhu\openDiagram\physchem\python>python search_lib.py
running search main
DEMO
project files not available for  C:\Users\DELL\projects\openDiagram\physchem\resources\liion10
project files not available for  C:\Users\DELL\projects\openDiagram\python\diagrams\luke\ffml20
project files not available for  C:\Users\DELL\projects\openDiagram\physchem\resources\oil26
project files not available for  C:\Users\DELL\projects\CEVOpen/searches/oil186
project files not available for  C:\Users\DELL\projects\openDiagram/python/diagrams/satish/cct
project files not available for  C:\Users\DELL\projects\openVirus\miniproject\disease\1-part
project files not available for  C:\Users\DELL\projects\openDiagram/python/diagrams/rahul/diffprotexp
project files not available for  C:\Users\DELL\projects\worcester\synthesis
project files not available for  C:\Users\DELL\projects\worcester\explosion
project files not available for  C:\Users\DELL\projects\CEVOpen\minicorpora\activity
project files not available for  C:\Users\DELL\projects\CEVOpen\minicorpora\hydrodistil
project files not available for  C:\Users\DELL\projects\CEVOpen\minicorpora\invasive
project files not available for  C:\Users\DELL\projects\CEVOpen\minicorpora\plantpart
adding dictionary C:\Users\DELL\dictionary\ami3\animaltest.xml
Traceback (most recent call last):
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\util.py", line 308, in check_exists
    f = open(file, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DELL\\dictionary\\ami3\\animaltest.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 804, in <module>
    main()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 779, in main
    AmiSearch.plant_parts_demo()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 274, in plant_parts_demo
    ami_search = AmiSearch()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 72, in __init__
    self.ami_dictionaries = AmiDictionaries()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 636, in __init__
    self.create_search_dictionary_dict()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 648, in create_search_dictionary_dict
    self.make_ami3_dictionaries()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 724, in make_ami3_dictionaries
    self.add_with_check(item[0], item[1])
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 731, in add_with_check
    Util.check_exists(file)
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\util.py", line 312, in check_exists
    raise FileNotFoundError(str(file) + " should exist")
FileNotFoundError: C:\Users\DELL\dictionary\ami3\animaltest.xml should exist
```

**Comment by Radhu903** [comment]
```
C:\Users\DELL\Radhu\openDiagram\physchem\python>python search_lib.py
running search main
DEMO
project files not available for  C:\Users\DELL\projects\openDiagram\physchem\resources\liion10
project files not available for  C:\Users\DELL\projects\openDiagram\python\diagrams\luke\ffml20
project files not available for  C:\Users\DELL\projects\openDiagram\physchem\resources\oil26
project files not available for  C:\Users\DELL\projects\CEVOpen/searches/oil186
project files not available for  C:\Users\DELL\projects\openDiagram/python/diagrams/satish/cct
project files not available for  C:\Users\DELL\projects\openVirus\miniproject\disease\1-part
project files not available for  C:\Users\DELL\projects\openDiagram/python/diagrams/rahul/diffprotexp
project files not available for  C:\Users\DELL\projects\worcester\synthesis
project files not available for  C:\Users\DELL\projects\worcester\explosion
project files not available for  C:\Users\DELL\projects\CEVOpen\minicorpora\activity
project files not available for  C:\Users\DELL\projects\CEVOpen\minicorpora\hydrodistil
project files not available for  C:\Users\DELL\projects\CEVOpen\minicorpora\invasive
project files not available for  C:\Users\DELL\projects\CEVOpen\minicorpora\plantpart
adding dictionary C:\Users\DELL\dictionary\ami3\animaltest.xml
Traceback (most recent call last):
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\util.py", line 308, in check_exists
    f = open(file, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DELL\\dictionary\\ami3\\animaltest.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 831, in <module>
    main()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 804, in main
    AmiSearch.plant_parts_demo()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 289, in plant_parts_demo
    ami_search = AmiSearch()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 72, in __init__
    self.ami_dictionaries = AmiDictionaries()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 654, in __init__
    self.create_search_dictionary_dict()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 666, in create_search_dictionary_dict
    self.make_ami3_dictionaries()
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 749, in make_ami3_dictionaries
    self.add_with_check(item[0], item[1])
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\search_lib.py", line 756, in add_with_check
    Util.check_exists(file)
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\util.py", line 312, in check_exists
    raise FileNotFoundError(str(file) + " should exist")
FileNotFoundError: C:\Users\DELL\dictionary\ami3\animaltest.xml should exist
```
