### ISSUE TITLE
unable to run search_lib.py file

### ISSUE THREAD

**Issue by dheerajdhingani** [petermr/openDiagram#8]
I have tried with both anaconda or python but get this error.
`PS C:\Users\Mark\openDiagram\physchem\python> & C:/Users/Mark/AppData/Local/Programs/Python/Python39/python.exe c:/Users/Mark/openDiagram/physchem/python/search_lib.pyrunning search mainDEMOTraceback (most recent call last):  File "c:\Users\Mark\openDiagram\physchem\python\search_lib.py", line 760, in <module>    main()  File "c:\Users\Mark\openDiagram\physchem\python\search_lib.py", line 736, in main    AmiSearch.demo()  File "c:\Users\Mark\openDiagram\physchem\python\search_lib.py", line 270, in demo    ami_search = AmiSearch()  File "c:\Users\Mark\openDiagram\physchem\python\search_lib.py", line 54, in __init__    self.ami_projects = AmiProjects()  File "c:\Users\Mark\openDiagram\physchem\python\search_lib.py", line 387, in __init__    self.create_project_dict()  File "c:\Users\Mark\openDiagram\physchem\python\search_lib.py", line 391, in create_project_dict    self.add_with_check(AmiProjects.LIION10, os.path.join(PHYSCHEM_RESOURCES, "liion10"))  File "c:\Users\Mark\openDiagram\physchem\python\search_lib.py", line 408, in add_with_check    Util.check_exists(file)  File "c:\Users\Mark\openDiagram\physchem\python\util.py", line 291, in check_exists    assert os.path.exists(file), str(file) + " should exist"AssertionError: C:\Users\Mark\projects\openDiagram\physchem\resources\liion10 should exist`

**Comment by petermr** [comment]
The `liion10` should be part of the github repo:
```
pwd
/Users/pm286/projects/openDiagram/physchem/resources
(base) pm286macbook:resources pm286$ ls
liion10	oil26
(base) pm286macbook:resources pm286$ 
```
see: https://github.com/petermr/openDiagram/tree/master/physchem/resources/liion10

Make sure you are up to date with this repo.
