### ISSUE TITLE
unable to run search_lib.py

### ISSUE THREAD

**Issue by tlhahsn** [petermr/openDiagram#9]
C:\Users\talha\AppData\Local\Programs\Python\Python39\python.exe C:/Users/talha/openDiagram/physchem/python/search_lib.py
Traceback (most recent call last):
  File "C:\Users\talha\openDiagram\physchem\python\search_lib.py", line 6, in <module>
    from text_lib import TextUtil, AmiSection, WordFilter
  File "C:\Users\talha\openDiagram\physchem\python\text_lib.py", line 5, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

Process finished with exit code 1

**Comment by tlhahsn** [comment]
C:\Users\talha\AppData\Local\Programs\Python\Python39\python.exe C:/Users/talha/openDiagram/physchem/python/search_lib.py
running search main
DEMO
project files not available for  C:\Users\talha\projects\openDiagram\physchem\resources\liion10
project files not available for  C:\Users\talha\projects\openDiagram\python\diagrams\luke\ffml20
project files not available for  C:\Users\talha\projects\openDiagram\physchem\resources\oil26
project files not available for  C:\Users\talha\projects\CEVOpen/searches/oil186
project files not available for  C:\Users\talha\projects\openDiagram/python/diagrams/satish/cct
project files not available for  C:\Users\talha\projects\openVirus\miniproject\disease\1-part
project files not available for  C:\Users\talha\projects\openDiagram/python/diagrams/rahul/diffprotexp
project files not available for  C:\Users\talha\projects\worcester\synthesis
project files not available for  C:\Users\talha\projects\worcester\explosion
project files not available for  C:\Users\talha\projects\CEVOpen\minicorpora\activity
project files not available for  C:\Users\talha\projects\CEVOpen\minicorpora\hydrodistil
project files not available for  C:\Users\talha\projects\CEVOpen\minicorpora\invasive
project files not available for  C:\Users\talha\projects\CEVOpen\minicorpora\plantpart
adding dictionary C:\Users\talha\dictionary\ami3\animaltest.xml
Traceback (most recent call last):
  File "C:\Users\talha\openDiagram\physchem\python\util.py", line 308, in check_exists
    f = open(file, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\talha\\dictionary\\ami3\\animaltest.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\talha\openDiagram\physchem\python\search_lib.py", line 804, in <module>
    main()
  File "C:\Users\talha\openDiagram\physchem\python\search_lib.py", line 779, in main
    AmiSearch.plant_parts_demo()
  File "C:\Users\talha\openDiagram\physchem\python\search_lib.py", line 274, in plant_parts_demo
    ami_search = AmiSearch()
  File "C:\Users\talha\openDiagram\physchem\python\search_lib.py", line 72, in __init__
    self.ami_dictionaries = AmiDictionaries()
  File "C:\Users\talha\openDiagram\physchem\python\search_lib.py", line 636, in __init__
    self.create_search_dictionary_dict()
  File "C:\Users\talha\openDiagram\physchem\python\search_lib.py", line 648, in create_search_dictionary_dict
    self.make_ami3_dictionaries()
  File "C:\Users\talha\openDiagram\physchem\python\search_lib.py", line 724, in make_ami3_dictionaries
    self.add_with_check(item[0], item[1])
  File "C:\Users\talha\openDiagram\physchem\python\search_lib.py", line 731, in add_with_check
    Util.check_exists(file)
  File "C:\Users\talha\openDiagram\physchem\python\util.py", line 312, in check_exists
    raise FileNotFoundError(str(file) + " should exist")
FileNotFoundError: C:\Users\talha\dictionary\ami3\animaltest.xml should exist

Process finished with exit code 1
